### ISSUE TITLE
use poetry instead of setup tools as package manager

### ISSUE THREAD

**Issue by FabienArcellier** [streamsync-cloud/streamsync#230]
The migration to poetry is done in an iso-functional way. The goal is to automate the management of the development environment and fix dev dependencies to make working together easier.

[more about why I advocate to use poetry as packaging system](https://dev.to/farcellier/i-migrate-to-poetry-in-2023-am-i-right--115)

### Check

* [x] a user can run `streamsync hello` after installing the package with `pip install streamsync[ds]`
* [x] the user can still install optional dependencies `pip install streamsync[ds]`
* [x] a developper can run `bash ./build.sh`
* [x] files referenced in `MANIFEST.in` are present in the distribution package

### Todo

* [x] configure poetry
* [x] configure poetry to handle virtualenv in `.venv`
* [x] migrate the build.sh
* [x] remove MANIFEST.in because poetry handle all the files from src
* [x] modify CONTRIBUTING.md
* [x] remove the dependency group of `test`, use `build` instead
