### ISSUE TITLE
github action enforce PR continuous integration rules

### ISSUE THREAD

**Issue by FabienArcellier** [streamsync-cloud/streamsync#233]
continuous integration plays a full validation pipeline to verify the integrity of streamsync. This pipeline will condition the merge of a PR.

* [alfred-cli](https://github.com/FabienArcellier/alfred-cli) will be used as runner
* `github action` will be used as continuous integration platform

### Todo

* [x] configure github action for controlling branches and pull-requests on ubuntu (python 3.10, 3.11, 3.12)
* [x] configure github action for controlling branches and pull-requests on macos (python 3.10, 3.11, 3.12)
* [x] configure github action for controlling branches and pull-requests on windows (python 3.10, 3.11, 3.12)
* [x] implement the ``alfred ci.mypy`` command
* [x] implement the ``alfred ci.pytest`` command
* [x] implement the ``alfred build`` pipeline
* [x] implement the ``alfred ci`` pipeline
* [x] github action badges for continuous integration appear on the readme
